# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [6]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [11]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [19]:
print(np.__version__)
np.show_config()

1.20.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [27]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [44]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [53]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

Exception: File `'`python.py'` not found.

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [62]:
array = np.zeros(10)
array[4] = 1
array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [68]:
Z = np.arange(10, 50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [81]:
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [95]:
# np.reshape([3, 3])
np.arange(9).reshape(3,3)
# hint(9)
# answer(9)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [102]:
# Z = np.array([1,2,0,0,4,0])
np.nonzero([1,2,0,0,4,0])

# hint(10)
# answer(10)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [113]:
np.eye(3) # 単位行列(identity matrix)

# hint(11)
# answer(11)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [129]:
np.random.random((3,3,3))

# hint(12)
answer(12)

Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [138]:
Z = np.random.random((10, 10))

Zmin, Zmax = Z.min(), Z.max()
Zmin, Zmax

# hint(13)
# answer(13)

(0.015070738793465988, 0.9842693830017539)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [144]:
np.random.random(30).mean()

# hint(14)
# answer(14)

0.44220036233226884

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [160]:
Z = np.ones((10,10))
Z[1:-1, 1:-1] = 0
Z

# hint(15)
# answer(15)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [172]:
Z = np.ones((5,5))
Z= np.pad(Z, pad_width=1,mode='constant', constant_values=0)
Z

# hint(16)
# answer(16)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [177]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

# hint(17)
# answer(17)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [197]:
Z = np.diag(1 + np.arange(4),k=-1)
Z

# hint(18)
# answer(18)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [215]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

# hint(19)
# answer(19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [225]:
print(np.unravel_index(99, (6,7,8)))


# hint(20)
# answer(20)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [233]:
np.tile(np.array([[0,1],[1,0]]), (4,4)) # 繰り返し表示(np.tile)

# hint(21)
# answer(21)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [261]:
np.random.seed(seed=1)
x = np.random.random((5,5))
(x - np.mean(x) ) / np.std(x) # (x - x.mean() / x.std()) でもOK!

# hint(22)
# answer(22)

array([[-0.08166511,  1.00240927, -1.57179097, -0.4915921 , -1.04765972],
       [-1.24215993, -0.906462  , -0.33708451, -0.15405956,  0.35365788],
       [-0.07390005,  0.87693577, -0.84143938,  1.56639833, -1.47431007],
       [ 0.82420869, -0.08065433,  0.42468899, -1.07042386, -0.86413849],
       [ 1.28984952,  1.88859468, -0.45194809,  0.90232398,  1.56022104]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [269]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
color

# hint(23)
# answer(23)

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [288]:
# x = np.random.random((5,3))
# y = np.random.random((3,2))
# x.dot(y)

Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# hint(24)
# answer(24)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [293]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


# hint(25)
# answer(25)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [308]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


# hint(26)
# answer(26)

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [319]:
Z = 3

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


# hint(27)
# answer(27)

False

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [336]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


# hint(28)
# answer(28)

nan
0
[-9.22337204e+18]


/var/folders/nq/rrkdqc797md78cknwf3sbjq00000gn/T/ipykernel_56792/1484691816.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/nq/rrkdqc797md78cknwf3sbjq00000gn/T/ipykernel_56792/1484691816.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [467]:
Z = np.random.uniform(-10, 10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


# hint(29)
# answer(29)


# a = np.arange(9).reshape(3,3)
# # np.flip(a, axis=1)
# np.flip(a, axis=1)

# a = np.random.rand(2)
# a

# a = np.random.randint(0,10, (3,3))
# print(a)
# np.diag(a)

# a = np.array([[0, 1], [1, 0]])
# np.tile(a, (1,4))

# a = np.random.randint(0,10,10)
# # print(a)
# np.bincount(a)

# np.repeat([2,9],8)

# a = np.arange(9)
# np.roll(a, 2)

# a = np.arange(9).reshape(3,3)
# a.flatten()

# a = np.array([[1,0,0,1], [2,2,3,4]])
# b = np.array([1,1,1,1])
# # np.concatenate((a,b), axis=1)
# np.vstack((a.flatten(),b))

# a = np.arange(10)
# b = np.repeat([1, -1],  5)
# np.copysign(a,b)

a = np.arange(10)
b = np.arange(5, 15)
np.intersect1d(a, b)

[-4. -9. -6.  4. -1.  1. -7.  2. 10.  7.]


array([5, 6, 7, 8, 9])

#### 30. How to find common values between two arrays? (★☆☆)

In [475]:
a = 1 + np.arange(9)
b = np.arange(5)
np.intersect1d(a,b)

# hint(30)
# answer(30)

array([1, 2, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [490]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

# hint(31)
# answer(31)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [499]:
np.sqrt(-1) == np.emath.sqrt(-1)

# hint(32)
# answer(32)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [515]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

# hint(33)
# answer(33)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [518]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

# hint(34)
# answer(34)

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [538]:
A = np.ones(3)*1
B = np.ones(3) *2

np.add(A,B, out=B)
np.divide(A,2,out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)

# hint(35)
# answer(35)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [560]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z .astype(int))
print(np.floor(Z))


# hint(36)
# answer(36)

[4. 3. 6. 2. 4. 3. 6. 8. 4. 7.]
[4. 3. 6. 2. 4. 3. 6. 8. 4. 7.]
[4. 3. 6. 2. 4. 3. 6. 8. 4. 7.]
[4 3 6 2 4 3 6 8 4 7]
[4. 3. 6. 2. 4. 3. 6. 8. 4. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [579]:
Z = np.zeros((5,5))
Z += np.arange(5)
Z

# Z = np.tile(np.arange(0,5),(5,1))
# Z

# hint(37)
# answer(37)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [585]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

# hint(38)
# answer(38)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [598]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

# 0から1の間の10個の値を要素に持つが、0も1も要素に持たない配列を作る。
# 上記の方法では np.linspace() で線形に等間隔な0から1の間の10個の要素を持つ配列を生成する。
# endpoint=Falseはstop(ここでは11)を含むかどうかのフラグ。
# endpointを11に指定することで11番目の要素が1になるが、これを配列に含まないようにする。
# 最後に配列の1番目よりあとを選ぶことで0を含まない配列になる

# hint(39)
# answer(39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [613]:
Z = np.random.random(10)
Z.sort()
Z

# hint(40)
# answer(40)

array([0.1494468 , 0.16994071, 0.18395344, 0.42893233, 0.46283912,
       0.51417504, 0.61358869, 0.64831276, 0.7073166 , 0.87533273])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [626]:
Z = np.arange(10)
np.add.reduce(Z) # np.sum(Z)より速い


# hint(41)
# answer(41)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [639]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.allclose(A,B)
equal

equal = np.array_equal(A,B)
equal

# hint(42)
# answer(42)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [648]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

# hint(43)
# answer(43)

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [656]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

# hint(44)
# answer(44)

[0.11075035 0.4235086  0.79754631 0.37756449 0.80407258 0.85954627
 0.59755981 0.86559306 1.34971065 0.47966195]
[1.12735036 1.00866585 1.39184756 0.1645324  0.44997999 0.96590503
 0.43126205 0.51616575 0.79924943 1.50362438]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [671]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

# hint(45)
# answer(45)

[0.09834683 0.42110763 0.         0.53316528 0.69187711 0.31551563
 0.68650093 0.83462567 0.01828828 0.75014431]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [681]:
Z = np.zeros((5,5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
np.linspace(0,1,5)

# hint(46)
# answer(46)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [686]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

# hint(47)
# answer(47)

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [692]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

# hint(48)
# answer(48)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [699]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

# hint(49)
# answer(49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [712]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])



# hint(50)
# answer(50)

68


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [714]:


# hint(51)
# answer(51)

hint: dtype
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [715]:


# hint(52)
# answer(52)

hint: np.atleast_2d, T, np.sqrt


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [718]:

# hint(53)
# answer(53)

hint: view and [:] =
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)